/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OAMWindow.java
 *
 * Created on 12/04/2009, 20:07:18
 */
package jnesbr.gui.debugger;

import javax.swing.table.DefaultTableModel;
import jnesbr.util.JNesUtil;
import jnesbr.video.PPUControll;
import jnesbr.video.Ppu2C02;
import jnesbr.video.SpriteRAM;

/**
 *
 * @author Leandro
 */
public class OAMWindow extends javax.swing.JFrame {

    /** Creates new form OAMWindow */
    public OAMWindow() {
        initComponents();
    }
    private int row = 0;

    private void add(String yCoordinate, String tileNumber, String attributes,String xCoordinate) {
        int colIndex = 0;
        jTableOAM.setValueAt(yCoordinate, row, colIndex++);
        jTableOAM.setValueAt(tileNumber, row, colIndex++);
        jTableOAM.setValueAt(attributes, row, colIndex++);
        jTableOAM.setValueAt(xCoordinate, row, colIndex++);
        row++;
    }

    private void fillOAMTable() {
        SpriteRAM sprRAM = SpriteRAM.getInstance();
        int oamIndex = 0;
        for (int i = 0 ; i < 64 ; i++ ){
            String yCoordinate = "";
            String tileNumber = "";
            String attributes = "";
            String xCoordinate = "";
            
            yCoordinate = String.valueOf(sprRAM.get(oamIndex));
            if (Ppu2C02.getInstance().ppuControl.spriteSize==PPUControll.SPRITE8x8){
                tileNumber = JNesUtil.giveMeHexaStringFormattedWith2Space(sprRAM.get(oamIndex+1));
                String address = (Ppu2C02.getInstance().ppuControl.patternTableAddressSprites == PPUControll.VRAM0x0000)?"0000" : "1000";
                tileNumber += " Pattern="+address;
            }else{
                tileNumber = JNesUtil.giveMeHexaStringFormattedWith2Space(sprRAM.get(oamIndex+1)>>1);
                String address = ((sprRAM.get(oamIndex+1)&0) == 0)?"0000" : "1000";
                tileNumber += " Pattern="+address;
                //todo: bit 0 defines who is the owner pattern table???
            }
            short byte2 = sprRAM.get(oamIndex+2);
            String verticalFlip = (JNesUtil.giveMeBit7From(byte2)==0)?"Normal":"Mirror";
            String horizontalFlip = (JNesUtil.giveMeBit6From(byte2)==0)?"Normal":"Mirror";
            String backgroundPriority = (JNesUtil.giveMeBit5From(byte2)==0)?"Front":"Behind";
            String spritePalette = JNesUtil.giveMeBinaryStringFormattedWith2Space(JNesUtil.giveMeBit1From(byte2)<<1 | JNesUtil.giveMeBit0From(byte2));
            attributes = "Vertical flip="+verticalFlip
                    +", Horizontal flip="+horizontalFlip
                    +", Background prior="+backgroundPriority
                    +", Palette color="+spritePalette;

            xCoordinate = String.valueOf(sprRAM.get(oamIndex+3));
            add(yCoordinate, tileNumber, attributes, xCoordinate);
            oamIndex += 4;
        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOAM = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OAM - Sprite RAM");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTableOAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Y Coordinate Minus 1", "Tile Number", "Attributes", "X Coordinate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOAM.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableOAM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTableOAM.setModel(new DefaultTableModel(new String[]{"Y Coordinate", "Tile Number", "Attributes","X Coordinate"}, 64));
        jTableOAM.getColumnModel().getColumn(0).setResizable(false);
        jTableOAM.getColumnModel().getColumn(0).setMaxWidth(120);
        jTableOAM.getColumnModel().getColumn(1).setResizable(false);
        jTableOAM.getColumnModel().getColumn(1).setMaxWidth(120);
        jTableOAM.getColumnModel().getColumn(2).setResizable(false);
        jTableOAM.getColumnModel().getColumn(2).setMaxWidth(520);
        jTableOAM.getColumnModel().getColumn(3).setResizable(false);
        jTableOAM.getColumnModel().getColumn(3).setMaxWidth(120);
        fillOAMTable();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OAMWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOAM;
    // End of variables declaration//GEN-END:variables
}
