/*
This file is part of JNesBR.

JNesBR is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNesBR is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with JNesBR.  If not, see <http://www.gnu.org/licenses/>.
 */
package jnesbr.gui;

import jnesbr.gui.debugger.MemoryView;
import jnesbr.gui.debugger.RomHeader;
import jnesbr.gui.debugger.Debugger;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import jnesbr.core.Emulator;
import jnesbr.gui.debugger.MemoryVideoView;
import jnesbr.gui.debugger.PatternTableViewer;

/**
 * @author dreampeppers99
 */
public class Main extends javax.swing.JFrame {

    private Emulator emulator;

    /** Creates new form Main */
    public Main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMnuMain = new javax.swing.JMenuBar();
        jMnuFile = new javax.swing.JMenu();
        jMnuLoad = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMnuExit = new javax.swing.JMenuItem();
        jMnuDebugger = new javax.swing.JMenu();
        jMnuShowHeader = new javax.swing.JMenuItem();
        jMnuMemoryView = new javax.swing.JMenuItem();
        jMnuVideoMemoryView = new javax.swing.JMenuItem();
        jMnuPatternTableViewer = new javax.swing.JMenuItem();
        JmnuDebbugerShow = new javax.swing.JMenuItem();
        jMnuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JNesBR - an(other) NES emulator.");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setText("Run");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Stop");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jMnuFile.setText("File");

        jMnuLoad.setText("Load");
        jMnuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuLoadActionPerformed(evt);
            }
        });
        jMnuFile.add(jMnuLoad);
        jMnuFile.add(jSeparator1);

        jMnuExit.setText("Exit");
        jMnuFile.add(jMnuExit);

        jMnuMain.add(jMnuFile);

        jMnuDebugger.setText("Debugger");

        jMnuShowHeader.setText("Rom Header");
        jMnuShowHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuShowHeaderActionPerformed(evt);
            }
        });
        jMnuDebugger.add(jMnuShowHeader);

        jMnuMemoryView.setText("Memory Viewer");
        jMnuMemoryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMemoryViewActionPerformed(evt);
            }
        });
        jMnuDebugger.add(jMnuMemoryView);

        jMnuVideoMemoryView.setText("Video Memory Viewer");
        jMnuVideoMemoryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVideoMemoryViewActionPerformed(evt);
            }
        });
        jMnuDebugger.add(jMnuVideoMemoryView);

        jMnuPatternTableViewer.setText("Pattern Table Viewer");
        jMnuPatternTableViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPatternTableViewerActionPerformed(evt);
            }
        });
        jMnuDebugger.add(jMnuPatternTableViewer);

        JmnuDebbugerShow.setText("Show Debugger");
        JmnuDebbugerShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmnuDebbugerShowActionPerformed(evt);
            }
        });
        jMnuDebugger.add(JmnuDebbugerShow);

        jMnuMain.add(jMnuDebugger);

        jMnuAbout.setText("About");
        jMnuMain.add(jMnuAbout);

        setJMenuBar(jMnuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuLoadActionPerformed
        final JFileChooser fc = makeJFileChooser();
        int returnVal = fc.showOpenDialog(this);

        if (userChooseSomething(returnVal)) {
            File file = fc.getSelectedFile();
            FileChannel roChannel;
            ByteBuffer readbuffer = null;
            try {
                roChannel = new RandomAccessFile(file, "r").getChannel();
                try {
                    readbuffer = roChannel.map(FileChannel.MapMode.READ_ONLY, 0, (int) roChannel.size());
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

            emulator = Emulator.getInstance();
            emulator.load(readbuffer);
        } else {
            return;
        }
    }//GEN-LAST:event_jMnuLoadActionPerformed

    private void jMnuShowHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuShowHeaderActionPerformed
        RomHeader romHeaderFrame = new RomHeader();
        romHeaderFrame.setVisible(true);
    }//GEN-LAST:event_jMnuShowHeaderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMnuMemoryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMemoryViewActionPerformed
        MemoryView mv = new MemoryView();
        mv.setVisible(true);
    }//GEN-LAST:event_jMnuMemoryViewActionPerformed

    private void JmnuDebbugerShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmnuDebbugerShowActionPerformed
        Debugger cp = new  Debugger();
        cp.setVisible(true);
    }//GEN-LAST:event_JmnuDebbugerShowActionPerformed

    private void jMnuVideoMemoryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVideoMemoryViewActionPerformed
        MemoryVideoView mvv = new MemoryVideoView();
        mvv.setVisible(true);
    }//GEN-LAST:event_jMnuVideoMemoryViewActionPerformed

    private void jMnuPatternTableViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPatternTableViewerActionPerformed
        PatternTableViewer ptv = new PatternTableViewer();
        ptv.setVisible(true);
    }//GEN-LAST:event_jMnuPatternTableViewerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        File file =new File("roms/SuperMarioBros(E)[a1].nes");
            FileChannel roChannel;
            ByteBuffer readbuffer = null;
            try {
                roChannel = new RandomAccessFile(file, "r").getChannel();
                try {
                    readbuffer = roChannel.map(FileChannel.MapMode.READ_ONLY, 0, (int) roChannel.size());
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }

            emulator = Emulator.getInstance();
            emulator.load(readbuffer);
    }//GEN-LAST:event_formWindowOpened

    private boolean userChooseSomething(int returnVal) {
        return returnVal == JFileChooser.APPROVE_OPTION;
    }

    private JFileChooser makeJFileChooser() {
        final JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Open NES File");
        fc.setCurrentDirectory(new java.io.File("."));
        return fc;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JmnuDebbugerShow;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMnuAbout;
    private javax.swing.JMenu jMnuDebugger;
    private javax.swing.JMenuItem jMnuExit;
    private javax.swing.JMenu jMnuFile;
    private javax.swing.JMenuItem jMnuLoad;
    private javax.swing.JMenuBar jMnuMain;
    private javax.swing.JMenuItem jMnuMemoryView;
    private javax.swing.JMenuItem jMnuPatternTableViewer;
    private javax.swing.JMenuItem jMnuShowHeader;
    private javax.swing.JMenuItem jMnuVideoMemoryView;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
